### PR TITLE
Pre-release: 0.20.60-d994

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
@conda-forge-admin, please rerender

**Comment by sebastian-luna-valero** [comment]
@conda-forge-admin, please rerender

**Comment by sebastian-luna-valero** [comment]
Hi @mohammad-akhlaghi 

Here are the outcomes of my tests.
* As discussed in https://github.com/conda-forge/gnuastro-feedstock/issues/28 there is a way to build pre-releases. AFAIK, this only means working on a `dev` branch and adding the `-dev` suffix to the package name. This is what I did on this PR.
* Issue 1: the `.tar.lz` extension is not recognized by `conda` and therefore I need to manually download and extract the source code. Valid extensions are `.tar.gz`, `.zip`, `.tar.bz2`, `.tar.xz`. Would it be possible to release `gnuastro` using one of those?
* Issue 2: conda didn't like the `0.20.60-d994` version number; in particular the `-d994` suffix. If possible, avoid using these kind of suffixes in the future.
* Issue 3: the `astmknoise` was no longer found, is this expected with this new version of `gnuastro`? I have temporarily removed from the test section.

Please let me know your thoughts.

Best regards,
Sebastian

**Comment by mohammad-akhlaghi** [comment]
Wonderful, thanks a lot :clap: 

I will try to reproduce these steps on another tarball and if I was able to reproduce the build, then I'll close this merge request (I am traveling now).

About issue 3, indeed, the `astmknoise` executable has been removed in this version of Gnuastro (because its features were present in a more complete way in other executables :wink:). This is described in the announcement, so users will know about it :wink:.

Thanks again,
Mohammad

**Comment by mohammad-akhlaghi** [comment]
Thanks a lot @sebastian-luna-valero for the nice checklist! I was able to replicate the process in #38 and confirm the build :smiley:. I am therefore closing this test build.

**Pull request closed without merging**
