### PR TITLE
Test build for next official version of Gnuastro

### PR DESCRIPTION
**Pull request by mohammad-akhlaghi**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mohammad-akhlaghi** [comment]
@sebastian-luna-valero: in preparation for the next official release of Gnuastro, I prepared this test merge request; but even before it starts the work, it is complaining that: "_No hosted parallelism has been purchased or granted. To request a free parallelism grant, please fill out the following form https://aka.ms/azpipelines-parallelism-request_".

Having a fast search, I noticed some questions like [this on stackoverflow](https://stackoverflow.com/questions/68405027/how-to-resolve-no-hosted-parallelism-has-been-purchased-or-granted-in-free-tie) which dates back to 2021. But I had done this process just a few months ago for the previous release and things went smoothly.

Do you have any idea why this is happening?

**Comment by sebastian-luna-valero** [comment]
First time I see this message @mohammad-akhlaghi 

I will start with a simple check and then troubleshoot further as time allows

**Comment by sebastian-luna-valero** [comment]
@conda-forge-admin, please rerender

**Comment by sebastian-luna-valero** [comment]
xref: https://github.com/conda-forge/status/issues/181

**Comment by mohammad-akhlaghi** [comment]
Thanks a lot @sebastian-luna-valero :+1:,

**Comment by sebastian-luna-valero** [comment]
@conda-forge-admin, please rerender

**Comment by sebastian-luna-valero** [comment]
@conda-forge-admin, please restart ci

**Comment by sebastian-luna-valero** [comment]
@mohammad-akhlaghi it seems to be working now

**Comment by mohammad-akhlaghi** [comment]
Wonderful! Thanks a lot @sebastian-luna-valero.

So the problem wasn't in Gnuastro, only in the Github CI.

Since this was just a test build, I am closing this issue and in a few days, we'll have Gnuastro 0.23 :smiley:.

**Pull request closed without merging**
